### ISSUE TITLE
Private beta - want someone else to try it?

### ISSUE THREAD

**Issue by joshtrichards** [carlcs/craft-footnotes#2]
Howdy - was getting ready to implement footnotes on my Craft-based site when research turned up your repo. Any chance you want someone else to try it out? I'd be happy to install and implement it on my site. Looks like just the readme is available in the public repo at the moment though. :)

-jr

**Comment by RobErskine** [comment]
Bump. Would also love to help test it out if possible. 👍

**Comment by jackbeckwith** [comment]
I'd love to try this as well!
