### ISSUE TITLE
Craft 3 version?

### ISSUE THREAD

**Issue by michaelroper** [carlcs/craft-footnotes#3]
Hey Christian! Not sure if this ever got an official release, but we somehow managed to get a copy of it along the way, and use it on our site. So I was wondering - did you have any plans to update it for Craft 3? 

If not, I might have a crack at it if that's okay with you - it's the last plugin on our "can we upgrade yet?" list!

**Comment by carlcs** [comment]
Yes! A private Craft 3 version already exists, and there will finally be a proper release now that Redactor has gotten some good updates.

**Comment by carlcs** [comment]
I just released a beta for Craft 3. The documentation is still missing but here is some example code for usage in Twig: [footnotes-v2.0.0-beta.1.md](https://gist.github.com/carlcs/a8c51bb7bbeb3350e549a6ba3cd27f7a).

**Comment by E2design** [comment]
Can we participate in the private beta for Craft3? Urgently looking for a footnotes solution with Redactor.

**Comment by carlcs** [comment]
@E2design it’s not private. The beta install instructions are in the v2 branch https://github.com/carlcs/craft-footnotes/tree/v2

**Comment by carlcs** [comment]
Probably better to leave this open as long as the plugin is in beta.
