### ISSUE TITLE
Option to render notes even when they’re not referenced

### ISSUE THREAD

**Issue by ockam** [carlcs/craft-footnotes#8]
Thanks a lot for this plugin!

Would it be possible to force `getFootnotesHtml()` to render all notes even when they are not referenced in the main text?

**Comment by carlcs** [comment]
Not sure I understand how you intend to use the plugin, so I created a feature branch to work on this. To start I added a param named `raw` to the `getFootnotes()` function (see https://github.com/carlcs/craft-footnote/commit/f873d56), which you can use like so:

```twig
{% for key, note in getFootnotes(raw=true) %}
    <pre>{{ dump({ key: key, note: note }) }}</pre>
{% endfor %}
```

**Comment by carlcs** [comment]
The branch is pushed to Packagist, so you should be able to install with:

```
composer require carlcs/craft-footnote:dev-feature/get-raw-footnotes
```

**Comment by ockam** [comment]
Sometimes, editors add notes without creating a reference to it in the main text.

In my case, I want them to render anyway but this imply 2 things:

1. every note is rendered
2. but the back reference link is not rendered if it doesn’t exist

**Comment by ockam** [comment]
We’re almost there with the `raw` option you added. The only piece missing is a way to use the renderListTemplate.

If you can add a `renderAll` option to `getFootnotesHtml`, this could be pass down to `getFootnotes` and `renderListTemplate`

```
    public function getFootnotesHtml($template = null, $articleId = '', $renderAll = false): string
    {
        $footnotes = $this->getFootnotes($articleId, $renderAll);

        if (!$footnotes) {
            return '';
        }

        $variables = [
            'footnotes' => $footnotes,
            'renderAll' => , $renderAll,
        ];

        return $this->renderListTemplate($template, $variables);
    }
```
I’m sorry, I should make a real PR, but i’m in a bind right now. :)

**Comment by carlcs** [comment]
How do you want to display those un-referenced notes, in a separate list? Maybe it’d make more sense to have two dedicated functions then, `getFootnotes()` and `getUnreferencedFootnotes()`.

I’m asking because the sort order of referenced notes is defined by the order of appearance of references, sort order of notes passed to `setDefinitions()` and `parseDefinitions()` doesn’t matter. So this makes it a bit unclear what to do with un-referenced ones.

https://github.com/carlcs/craft-footnote/blob/f873d56ea70482ff4087abeabc6db1f1ae631942/src/services/Footnotes.php#L148
https://github.com/carlcs/craft-footnote/blob/f873d56ea70482ff4087abeabc6db1f1ae631942/src/services/Footnotes.php#L188-L190

The `getFootnotesHtml()` function should probably be deprecated, as I learned that most plugin users are using their own markup anyways and passing the notes returned from `getFootnotes()` to a Twig include.

**Comment by ockam** [comment]
Oh, I missed to ordering bit.

Yes, getting unreferenced notes in a separate list is a good idea.

**Comment by carlcs** [comment]
I just pushed an update to our branch where I removed the `raw` param and added `includeUnmatched` instead: https://github.com/carlcs/craft-footnote/commit/9f85deb

In my template I can use it like so:

```twig
{% set footnotes = getFootnotes(includeUnmatched=true) %}

{{ include('_footnotes/list.html', { footnotes: footnotes|filter(note => note.noteId) }) }}
{{ include('_footnotes/list.html', { footnotes: footnotes|filter(note => not note.noteId) }) }}
```

**Comment by ockam** [comment]
You rock!

**Comment by carlcs** [comment]
Published a new release. Thanks for suggestion this feature! 👍

**Comment by ockam** [comment]
Works perfectly. Thanks a lot for the quick refactor!

**Comment by ockam** [comment]
If someone stumble upon this and want a quick template to use, here’s what I came up with.

In my entry template, assuming footnotes has been previously initialized (see docs):
```
      {% set footnotes = getFootnotes(includeUnmatched=true) %}
      <div class="footnotes">
        <ol>
          {{ include('_includes/footnotes-list-item', { footnotes: footnotes|filter(note => note.noteId) }) }}
          {{ include('_includes/footnotes-list-item', { footnotes: footnotes|filter(note => not note.noteId) }) }}
        </ol>
      </div>
```
and the list-item template:
```
{% for fn in footnotes %}
  {% set id = fn.noteId ? 'id="' ~ (fn.articleId ? fn.articleId ~ '-') ~ 'fn-' ~ fn.noteId ~ '"' : '' %}
  <li {{ id|raw }} class="footnotes-item">
    {{ fn.noteText|raw }}
    {% if fn.noteId %}
      {% for markerId in 0..fn.markerCount %}
        <a href="#{{ fn.articleId ? fn.articleId ~ '-' }}fnref-{{ fn.noteId }}{{ markerId ? '-' ~ markerId }}">&#x21a9;&#xfe0e;</a>
      {% endfor %}
    {% endif %}
  </li>
{% endfor %}
```
